version: "3.8"
services:
#  db:
#    image: mysql
#    container_name: db_docker_sf
#    restart: always
#    volumes:
#      - db-data:/var/lib/mysql
##    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
##    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_HOST=localhost
#      - MYSQL_PORT=3306
##      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#    ports:
#      - "3309:3306"
#    networks:
#      - dev

  php:
    build: ./docker/php # on build le dockerfile dans php/
    container_name: www_docker_sf
    user: "1000:1000"
    #    user: ${CURRENT_UID}
    ports:
      - "8080:8000"
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - dev

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:13-alpine
    container_name: db_docker_sf
    environment:
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dev
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  dev:

volumes:
  db-data:

